-- プロジェクトテーブルの作成
create table if not exists projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text
);

-- カテゴリーテーブルの作成
create table if not exists categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  project_id bigint references projects(id) on delete cascade not null
);

-- タスクテーブルの作成
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  status text default 'not-started' check (status in ('not-started', 'in-progress', 'completed')) not null,
  category_id bigint references categories(id) on delete cascade not null,
  memo text,
  attachments text[],
  checked_by text[]
);

-- サンプルデータの挿入
-- プロジェクト1: 新築工事
insert into projects (name, description) values 
('新築工事', '2階建て住宅の新築工事プロジェクト');

-- プロジェクト1のカテゴリー
insert into categories (name, project_id) values 
('基礎工事', (select id from projects where name = '新築工事')),
('躯体工事', (select id from projects where name = '新築工事')),
('内装工事', (select id from projects where name = '新築工事')),
('外構工事', (select id from projects where name = '新築工事'));

-- プロジェクト1のタスク
insert into tasks (name, status, category_id, memo) values 
('地盤調査', 'completed', (select id from categories where name = '基礎工事'), '地盤強度は十分あり'),
('基礎配筋', 'in-progress', (select id from categories where name = '基礎工事'), null),
('コンクリート打設', 'not-started', (select id from categories where name = '基礎工事'), null),
('木材加工', 'not-started', (select id from categories where name = '躯体工事'), null),
('建て方', 'not-started', (select id from categories where name = '躯体工事'), null),
('クロス貼り', 'not-started', (select id from categories where name = '内装工事'), null),
('フローリング施工', 'not-started', (select id from categories where name = '内装工事'), null),
('植栽', 'not-started', (select id from categories where name = '外構工事'), null),
('フェンス設置', 'not-started', (select id from categories where name = '外構工事'), null);

-- プロジェクト2: リフォーム工事
insert into projects (name, description) values 
('リフォーム工事', '築30年マンションの全面改装工事');

-- プロジェクト2のカテゴリー
insert into categories (name, project_id) values 
('解体', (select id from projects where name = 'リフォーム工事')),
('設備工事', (select id from projects where name = 'リフォーム工事')),
('仕上げ工事', (select id from projects where name = 'リフォーム工事'));

-- プロジェクト2のタスク
insert into tasks (name, status, category_id, memo) values 
('既存解体', 'not-started', (select id from categories where name = '解体'), null),
('廃材処理', 'not-started', (select id from categories where name = '解体'), null),
('給排水工事', 'not-started', (select id from categories where name = '設備工事'), null),
('電気工事', 'not-started', (select id from categories where name = '設備工事'), null),
('壁紙貼替', 'not-started', (select id from categories where name = '仕上げ工事'), null),
('床材張替', 'not-started', (select id from categories where name = '仕上げ工事'), null); 